### ISSUE TITLE
Why I do not success to get internet access ?

### ISSUE THREAD

**Issue by pcouderc12** [nopnop2002/esp-idf-wifi-apsta#3]
I am trying to use this example as basic router (using master esp-idf).

From an Androïd device, I connect  to the  esp32, I get an 192.168.4.2 IP address, but "no internet access".

What do I miss ?

I see no dns data, but I suppose it comes from the DHCP of the STA...

I have tried too to add the following options (from martin-ger router) that were not set:
*Component config -> LWIP > [x] Enable copy between Layer2 and Layer3 packets.
*Component config -> LWIP > [x] Enable IP forwarding.
*Component config -> LWIP > [x] Enable NAT (new/experimental).

but it changes nothing...

What do I miss ?

**Comment by nopnop2002** [comment]
This sample is simply a sample of running AP mode and STA mode at the same time with one ESP.

If you want router functionality, you need to add functionality.

An implementation of a router using two interfaces can be found here.
https://github.com/espressif/esp-idf/tree/master/examples/ethernet/eth2ap

**Comment by pcouderc12** [comment]
OK, thank you !
